### ISSUE TITLE
Провести поиск и анализ существующих онлайн калькуляторов

### ISSUE THREAD

**Issue by MikhailovAlexander** [OMMAT-HSE/algoscalc-docs#1]
Найти не менее 3 аналогов, описать каждый из них, выбрать критерии для сравнения и составить сравнительную таблицу

**Comment by KateMarmysh** [comment]
**Рассматриваемые онлайн калькуляторы:**
1. https://math.semestr.ru/
2. https://www.calculat.org/ru/
3. https://geleot.ru/
4. https://ru.onlinemschool.com/math/assistance/
5. https://zaochnik.com/online-calculators/
6. https://calculatorium.ru/

**Comment by KateMarmysh** [comment]
Для проверки скорости сайтов использовался сайт:
https://pr-cy.ru/speed_test/
