### ISSUE TITLE
Разработать 1 главу группового отчета по проекту

### ISSUE THREAD

**Issue by MikhailovAlexander** [OMMAT-HSE/algoscalc-docs#25]

**Comment by KateMarmysh** [comment]
Ссылка на отчет:
https://docs.google.com/document/d/1G6eNb2eaUeoViJpViUbBjlUj4w_jzmpb5ak1XRM30dM/edit

**Comment by ValeriAnnenkova** [comment]
Первая глава готова, переходите по ссылке выше

**Comment by MikhailovAlexander** [comment]
Глвава супер! Задачу закрываю.
