### ISSUE TITLE
Подобрать набор алгоритмов для MVP версии онлайн-калькулятора

### ISSUE THREAD

**Issue by MikhailovAlexander** [OMMAT-HSE/algoscalc-docs#29]
Алгоритмы для разрабатываемого онлайн-калькултора могут иметь различные входные параметры и возвращать результат, состоящий из различных элементов. Требуется подобрать для MVP версии такой минимальный набор алгоритмов, который позволит протестировать работу и отображение алгоритмов с различными вариантами входных и выходных данных.

Варианты формы входных и выходных данных:
1. SCALAR - отдельное значение
2. LIST - список значений
3. MATRIX - двумерная таблица со значениями

Варианты типов входных и выходных данных:
1. INT - целое число
2. FLOAT - число с плавающей точкой
3. STRING - строка
4. BOOL - логическое значение

**Comment by MikhailovAlexander** [comment]
## Критерии тестирования входных и выходных данных

| №     | Критерий                         | А1  | А2  | А3  | А4  | А5  | А6  | А7  |
|-------|----------------------------------|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1     | **Входные данные (параметры)**   |  -  |  -  |  -  |  -  |  -  |  -  |  -  |
| 1.1   | **Форма данных**                 |  -  |  -  |  -  |  -  |  -  |  -  |  -  |
| 1.1.1 | SCALAR                           |  +  |  +  |  +  |     |  +  |  +  |     |
| 1.1.2 | LIST                             |     |     |     |     |     |     |  +  |
| 1.1.3 | MATRIX                           |     |     |     |  +  |     |     |     |
| 1.2   | **Тип данных**                   |  -  |  -  |  -  |  -  |  -  |  -  |     |
| 1.2.1 | INT                              |  +  |  +  |     |  +  |     |     |  +  |
| 1.2.2 | FLOAT                            |     |     |  +  |     |     |  +  |     |
| 1.2.3 | STRING                           |     |     |     |     |  +  |     |     |
| 1.2.4 | BOOL                             |     |     |  +  |     |     |     |     |
| 1.3   | **Количество**                   |  -  |  -  |  -  |  -  |  -  |  -  |     |
| 1.3.1 | 1 параметр                       |  +  |  +  |     |     |  +  |     |  +  |
| 1.3.2 | Больше 1 параметра               |     |     |  +  |  +  |     |  +  |     |
| 2     | **Выходные данные (результаты)** |  -  |  -  |  -  |  -  |  -  |  -  |     |
| 2.1   | **Форма данных**                 |  -  |  -  |  -  |  -  |  -  |  -  |     |
| 2.1.1 | SCALAR                           |  +  |     |  +  |     |  +  |  +  |  +  |
| 2.1.2 | LIST                             |     |  +  |     |     |     |     |  +  |
| 2.1.3 | MATRIX                           |     |     |     |  +  |     |     |     |
| 2.2   | **Тип данных**                   |  -  |  -  |  -  |  -  |  -  |  -  |     |
| 2.2.1 | INT                              |  +  |  +  |     |  +  |  +  |     |  +  |
| 2.2.2 | FLOAT                            |     |     |  +  |     |     |     |     |
| 2.2.3 | STRING                           |     |     |     |     |     |  +  |     |
| 2.2.4 | BOOL                             |     |     |     |     |     |     |  +  |
| 2.3   | **Количество**                   |  -  |  -  |  -  |  -  |  -  |  -  |     |
| 2.3.1 | 1 результат                      |  +  |  +  |     |  +  |  +  |  +  |     |
| 2.3.2 | Больше 1 результата              |     |     |  +  |     |     |     |  +  |

## Список алгоритмов
А1 - Числа Фибоначчи - скалярный целочисленный параметр - номер числа, скалярный целочисленный результат - значение заданного числа Фибоначчи.

А2 - Спиок чисел Фибоначчи - скалярный целочисленный параметр - номер числа, результат список целых чисел - список чисел Фибоначчи от 1 до заданного.

А3 - Умножение двух чисел с плавающей точкой - два входных параметра, числа с плавающей точкой, один результат, число с плавающей точкой. Софья Санникова. Заменил на алгоритм Расход топлива для поездки на заданное расстояние, входные парамеры с плавающей точкой и логический, выходные параметры с плавающей точкой 

А4 - Вычитание двух матриц - два входных параметра, матрицы с целыми числами, один результат, матрица с целыми числами. Долгунова Анна.

A5 - Подсчет количества подстрок входной строки - входной параметр строка, выходной параметр - целое число. Чепуштанов Дмитрий. 

А6 - Поиск корней квадратного уравнения - входные параметры три числа с плавающей точкой, на выходе строка со значениями корней или с сообщением, о том, что действительных корней нет. Новоселова Алиса.

А7 - Проверка ряда чисел на совершенность - входные параметры список целых чисел, выходные параметры - список целых чисел и логическое значение. Михайлов Александр.

**Comment by Dooooooll** [comment]
А4 - Вычитание двух матриц - два входных параметра, матрицы, один результат, матрица. Долгунова Анна.

**Comment by MikhailovAlexander** [comment]
Все выбранные алгоритмы разработаны
