### ISSUE TITLE
Разработать план тестирования

### ISSUE THREAD

**Issue by MikhailovAlexander** [OMMAT-HSE/algoscalc-docs#33]

**Comment by ValeriAnnenkova** [comment]
1. Что надо тестировать?
Необходимо провести тестирование онлайн калькулятора, который предоставляет функционал расчета расхода топлива, подсчета количества подстрок в строке, нахождения корней квадратного уравнения, вычитания матриц, проверки ряда чисел на совершенность и генерации чисел Фибоначчи.
2. Что будете тестировать?
В процессе тестирования необходимо проверить соответствие функциональным требованиям каждого алгоритма в калькуляторе. Это включает:
- расчет расхода топлива: проверка точности расчета при заданных значениях расстояния и других параметров
- подсчет количества подстрок в строке: проверка правильности подсчета подстрок в различных строках
- нахождение корней квадратного уравнения: проверка правильности вычисления корней для разных входных значений
- вычитание матриц: проверка правильности операции вычитания для различных матриц.
- проверка ряда чисел на совершенность: проверка правильности определения совершенных чисел в заданном ряде
- генерация чисел Фибоначчи: проверка правильности генерации чисел Фибоначчи до заданного числа
Также необходимо проверить соответствие нефункциональным требованиям, включая отзывчивость системы, ее надежность и соответствие пользовательского интерфейса требованиям.
3. Как будете тестировать?
В плане тестирования предусмотрены следующие виды тестирования:
- модульное тестирование: проведение отдельных тестов для каждого алгоритма калькулятора
- интеграционное тестирование: проверка взаимодействия различных алгоритмов и их работоспособности вместе
- функциональное тестирование: проверка соответствия каждого алгоритма функциональным требованиям
- нагрузочное тестирование: проверка производительности калькулятора при большом количестве запросов.
- тестирование пользовательского интерфейса: проверка удобства использования и соответствия интерфейса требованиям. 
Также будет использовано автоматизированное тестирование для повторяемых сценариев
4. Когда будете тестировать?
Тестирование будет проводиться в следующей последовательности:
- подготовка: подготовка тестового стенда, получение документации и требований, настройка тестовых сценариев (до 31.05.2023)
- тестирование: выполнение запланированных видов тестирования в соответствии с разработкой функциональности (01.06.2023 - 07.06.2023)
- анализ результатов: анализ полученных результатов, выявление и отчетность о найденных проблемах (до 09.06.2023)
5. Критерии начала тестирования:
- готовность тестовой платформы (тестового стенда)
- завершенность разработки требуемого функционала
- наличие всей необходимой документации
6. Критерии окончания тестирования:
Результаты тестирования удовлетворяют критериям качества продукта:
- требования к количеству открытых багов выполнены
- выдержка определенного периода без изменения исходного кода приложения
- выдержка определенного периода без открытия новых багов
7. Окружение тестируемой системы:
- Веб-сервер
- База данных 
- Программное обеспечение операционной системы Браузеры (например, Chrome, Firefox, Safari).
8. Необходимое для тестирования оборудование и программные средства:
- Тестовый стенд с доступом к веб-серверу и базе данных
- Компьютеры для запуска автоматизированных тестов
- Браузеры разных версий для проверки совместимости
9. Риски и пути их разрешения:
-    Риск: Неправильные результаты расчетов.
      Путь разрешения: Проверка алгоритмов расчетов на различных тестовых данных и сравнение результатов с ожидаемыми значениями.
-   Риск: Низкая производительность при большой нагрузке.
     Путь разрешения: Проведение нагрузочного тестирования, оптимизация алгоритмов и инфраструктуры сервера при необходимости.
-   Риск: Несоответствие интерфейса требованиям.
Путь разрешения: Проведение тестирования пользовательского интерфейса, внесение корректировок и улучшений.
