### ISSUE TITLE
Провести анализ предметной области (реализация онлайн калькуляторов)

### ISSUE THREAD

**Issue by MikhailovAlexander** [OMMAT-HSE/algoscalc-docs#4]
Описать предметную область, выделить основные понятия, определить варианты использования

**Comment by awDelya** [comment]
use-case (draft)

![Image](https://user-images.githubusercontent.com/48090876/229896218-063dc67e-71aa-4178-8e95-b308dd5f9892.png)

**Comment by MikhailovAlexander** [comment]
Нужен анализ с точки зрения использования онлайн-калькулятора, без учета того, что его будут дорабатывать студенты

**Comment by MikhailovAlexander** [comment]
Создал ветку для задачи https://github.com/OMMAT-HSE/algoscalc-docs/tree/task-4

**Comment by MikhailovAlexander** [comment]
Добавил UML модель Visual Paradigm https://github.com/OMMAT-HSE/algoscalc-docs/blob/task-4/uml-model/algoscalc-uml.vpp

**Comment by awDelya** [comment]
1. Поправила use case в отдельной uml модели https://github.com/OMMAT-HSE/algoscalc-docs/blob/task-4/uml-model/algoscalc-uml_v2.vpp
2. Добавила [файл](https://github.com/OMMAT-HSE/algoscalc-docs/blob/task-4/drafts/Анализ%20предметной%20области%20(реализация%20онлайн%20калькуляторов).md) с описанием use case и спецификаций вариантов использования (только для вариантов, имеющих связь include).

**Comment by awDelya** [comment]
1. Поправила файл по замечаниям.
2. Добавила описание концептуальной модели алгоритма.
3. Изменила концептуальную модель алгоритма для сущности "Сложность алгоритма"
