### ISSUE TITLE
Разработать прототип системы (макет)

### ISSUE THREAD

**Issue by Demanoed** [OMMAT-HSE/algoscalc-docs#41]
Необходимо разработать прототип системы, например в Figma, с использованием компонентов MUI Material Ui. 

Компоненты MUI для Figma: https://www.figma.com/community/file/912837788133317724/MUI-for-Figma-(Material-UI%2C-Joy-UI%2C-MUI-X)

**Comment by Demanoed** [comment]
Документация по компонентам MUI тут: https://mui.com/material-ui/getting-started/overview/ - скорее всего не пригодится, хотя возможно сможете найти какие-то компоненты, каких не будет в компонентах выше.

**Comment by Demanoed** [comment]
У каждого алгоритма, когда открывается страница с алгоритмом, минимально должны быть:
1) Название алгоритма;
2) Описание алгоритма;
3) Автор алгоритма;
4) Необходимые поля для ввода параметров;
5) Вывод ответа.

Данный список можете смело расширять, я указал минимум :) Если будут вопросы, то пишите :)

**Comment by ValeriAnnenkova** [comment]
Ссылка на прототип
https://www.figma.com/file/47PgLJD7mpWvvZxNIZkOhZ/Разработка-прототипа?node-id=0-1&t=WSicgLgTT5jyQM76-0

**Comment by KateMarmysh** [comment]
Нужно доработать в прототипе следующие моменты (обсудили 20.04)

Добавить в прототип возможные варианты входных и выходных данных:
1) отдельное значение (скалярное)
2) список значений
2) двумерная матрица

Типы данных:
1) целое
2) плавающая точка
3) текст
4) да / нет (галочка, например - округлять результат)

Добавить сообщение об ошибке (модальное окно)

**Comment by KateMarmysh** [comment]
Описание разработанного прототипа - в последнем параграфе первой главы отчета.
Отчет по ссылке: https://docs.google.com/document/d/1G6eNb2eaUeoViJpViUbBjlUj4w_jzmpb5ak1XRM30dM/edit?usp=sharing
