### ISSUE TITLE
Исправить код в алгоритме fuel_consumption

### ISSUE THREAD

**Issue by KateMarmysh** [OMMAT-HSE/algoscalc-docs#53]
В алгоритме "Расход топлива для поездки на заданное расстояние" исправить код, чтобы значение расхода топлива (параметр "Средний расход топлива (л/100км)") делилось на 100, а цена в результате (поле вывода с заголовком "Стоимость топлива (руб)") округлялась только до 2 знаков после запятой (без флага "Округлить результат").

Алгоритм:
"name": "fuel_consumption",
"title": "Расход топлива для поездки на заданное расстояние"

**Comment by MikhailovAlexander** [comment]
Данную задачу включил в этп тестирования.

Для исправления ошибки в исходном коде серверной части онлайн-калькулятора создал зачу в репозитории algoscalc-back https://github.com/OMMAT-HSE/algoscalc-back/issues/22

**Comment by MikhailovAlexander** [comment]
Алгоритм доработан. Доработки перенесены на тестовый стенд.
Просьба проверить.

**Comment by KateMarmysh** [comment]
Проверила, все работает корректно
