### ISSUE TITLE
Отчет об ошибке №

### ISSUE THREAD

**Issue by MikhailovAlexander** [OMMAT-HSE/algoscalc-docs#54]
**Отчет об ошибке №54**

Тестируемая система: Онлайн-калькулятор, расположенный по адресу https://test.ommat.ru/algorithm?alg=fuel_consumption

Среда обнаружения: Google Chrome, Версия 114.0.5735.110 (Официальная сборка), (64 бит); ОС Майкрософт Windows 10 Домашняя, Версия	10.0.19045 Сборка 19045

Время обнаружения: 06.06.2023 / 17:00

Тестировщик: Мармыш Екатерина Сергеевна

Программист: Михайлов Александр Витальевич

**Калькулятор не позволяет вводить значения int в поля ввода входных данных**

Статус дефекта: выявлен.

Серьезность дефекта: Блокирующий (Blocker)

Приоритет дефекта: Высокий (High)

Подготовительные действия: Запустить браузер Google Chrome, Версия 114.0.5735.110. Перейти на тестовую страницу продукта Онлайн-калькулятор (https://test.ommat.ru/). 

Воспроизведение дефекта: Выбрать в меню, расположенном в левой части страницы алгоритм "Расход топлива для поездки на заданное расстояние" (возможен также выбор этого алгоритма в плитках, расположенных под блоком описания продукта на главной странице сайте). Ввести в поля ввода значений целые положительные числа, например, в поле с заголовком "Сколько хотите проехать": 500; в поле с заголовком "Средний расход топлива (л/100км)": 10, в поле с заголовком "Стоимость 1 л. топлива (руб)": 48. И нажать кнопку "ПОЛУЧИТЬ РЕЗУЛЬТАТ".

Фактический результат: Уведомление об ошибке "Произошла ошибка! Тип данных для значения не соответствует типу float"

Ожидаемый результат: В блоке вывода результата выводится результат расчета (в поле с заголовком "Потребуется топлива (л)": 50; в поле с заголовком "Стоимость топлива (руб)": 2400.

Подтверждение: выскакивающее уведомление об ошибке, описанное выше.

Классификация: #fuel_consumption #test #ommat

Комментарии: 

![Image](https://user-images.githubusercontent.com/126710416/243692961-aeb4bb5c-4a89-4f33-ad85-c43f04e94e99.png)

**Comment by MikhailovAlexander** [comment]
Приведение целого числа к числу с плавающей точкой безопасно, соответственно параметры с типом данных float должны коректно обрабатывать значения типа int.

Необходима доработка серверной части онлайн-калькулятора, создал задачу https://github.com/OMMAT-HSE/algoscalc-back/issues/24.

**Comment by MikhailovAlexander** [comment]
Ошибка исправлена. Доработки перенесены на тестовый стенд.
Просьба проверить.

**Comment by MikhailovAlexander** [comment]
Доработал контроль типов данных для матриц и списков

**Comment by KateMarmysh** [comment]
Проверено, все работает, ошибка исправлена
