### ISSUE TITLE
Создание презентации к выступлению

### ISSUE THREAD

**Issue by ValeriAnnenkova** [OMMAT-HSE/algoscalc-docs#57]
Презентация доступна по ссылке: https://docs.google.com/presentation/d/1kX-wVW_WWI5FYS_mDQKClas8VJgXEBjiNu59hylpPNc/edit?hl=ru#slide=id.g25197c88538_6_122

**Comment by MikhailovAlexander** [comment]
Добавил презентацию в репозиторий
https://github.com/OMMAT-HSE/algoscalc-docs/tree/Prod/%D0%9E%D1%82%D1%87%D0%B5%D1%82%D1%8B%20%D0%B8%20%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8
